### ISSUE TITLE
`readOnly` flag gets dropped from some refs in transforms

### ISSUE THREAD

**Issue by mccoyp** [tjprescott/openapi-diff#10]
In the Key Vault Keys service, we have a `KeyAttributes` type with a `recoveryLevel` property, which refers to a `DeletionRecoveryLevel` enum. This property is marked as `readOnly` in the original Swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.6-preview.1/keys.json#L1472

In the [TypeSpec conversion](https://github.com/Azure/azure-rest-api-specs/pull/29248) of the service spec, the `DeletionRecoveryLevel` enum is [defined as a string union](https://github.com/Azure/azure-rest-api-specs/blob/mccoyp/kv-keys-tsp/specification/keyvault/data-plane/Security.KeyVault.Keys/models.tsp#L86), and the `KeyAttributes` type again refers to it in a `recoveryLevel` property that is [marked as `readOnly`](https://github.com/Azure/azure-rest-api-specs/blob/mccoyp/kv-keys-tsp/specification/keyvault/data-plane/Security.KeyVault.Keys/models.tsp#L404). The OpenAPI spec that's compiled from the TypeSpec correctly marks this property accordingly: https://gist.github.com/mccoyp/f557213fdb5441bed7f5bbd3a3626163#file-openapi-json-L1979

The expected `"readOnly": true` flag goes missing in the transform though, in both [rhs](https://gist.github.com/mccoyp/50b81f9728e8692228098940e90b0d0b#file-rhs-json-L3797) and [rhs-inv](https://gist.github.com/mccoyp/972086631ce5a49d5300b0131df8ed00#file-rhs-inv-json-L4323). The flag is present in [lhs](https://gist.github.com/mccoyp/d61512fd4b9346be45b5c1de35160a6a#file-lhs-json-L3775) and not present in [lhs-inv](https://gist.github.com/mccoyp/392c25396e421fcd6c1edc3b34988e79#file-lhs-inv-json-L4270).

This can be locally reproduced by running `npm run diff` with a `.env` file that has the following settings configured:
```
LHS=<path to original common.json and keys.json Swagger files (see link at start of issue)>
RHS=<path to Security.KeyVault.Keys folder from TypeSpec conversion PR (see link at start of issue)>
COMPILE_TSP="true"
GROUP_VIOLATIONS="true"
TYPESPEC_COMPILER_PATH="<path to REST API specs repo clone>/node_modules/@typespec/compiler"
TYPESPEC_VERSION_SELECTOR="7.6-preview.1"
```

**Comment by tjprescott** [comment]
![image](https://github.com/user-attachments/assets/ddd3228b-7507-4410-a3e5-99cff2043d4c)
@mccoyp is this the diff you are talking about? I see this when I diff `lhs-inv.json` and `rhs-inv.json` which means that this diff is filtered out as irrelevant.

The `inv-diff.json` file contains an entry like this:
```
{
      "ruleResult": "N",
      "ruleName": "ignoreIrrelevantResponsePropertiesRule",
      "diff": {
        "kind": "D",
        "path": [
          "paths",
          "{vaultbaseurl}/deletedkeys",
          "get",
          "responses",
          "200",
          "schema",
          "properties",
          "value",
          "items",
          "properties",
          "attributes",
          "properties",
          "recoveryLevel",
          "readOnly"
        ],
        "lhs": true
      }
    },
```

The fact that readOnly was `true` on the LHS is irrelevant because that is the default.

**Comment by tjprescott** [comment]
Ah, actually, I see what is going on. The property is defined like so:
```
{
  "$ref": "..."
  "readonly": true
}
```
And the current logic only replaces the reference. It does not collect any sibling properties and apply them. I'll get this fixed in my current PR.
